BoopChat/boop

DESIGN.md
=> Added basic design and MVP spec

DESIGN.md
This will give us a chance to learn nodejs (I don't know it well either 😄)
=> Changing the backend to nodejs

client/src/screens/login.js, client/src/screens/sign_up.js, client/src/tests/login.test.js, client/src/tests/sign_up.test.js
These tests are to guide the functional requirements for the login and signup screens
=> add some tests for login and signup screens

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/node.js.yml
This PR adds a template for PR submissions, which should guide in how to detail PRs
Additionally, this PR adds an automated test to be done on all future PRs
=> House keeping

.gitignore, server/app.js, server/config/sample_config.json, server/controllers/Users.js, server/migrations/20210901160713-create-tables.js, server/models/Contact.js, server/models/Conversation.js, server/models/Message.js, server/models/Participant.js, server/models/SigninOption.js, server/models/User.js, server/models/index.js, server/package.json, server/queries/create-tables.sql, server/queries/drop-tables.sql, server/routes/index.js, server/routes/users.js
1. I deployed a db in docker:
docker run -d -p 5432:5432 --name "container-name" -e POSTGRES_PASSWORD="database-password" -e POSTGRES_DB="database-name" -e POSTGRES_USER="database-user" postgres 
(Change the variables in quotes + remove quotes)
2. Created the tables using: ./node_modules/.bin/sequelize db:migrate 
3. Ran the server using: npm run dev
4. Used the [Thunder Client](https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client) VSCode extension to test the users routes. Here's a [JSON file](https://drive.google.com/file/d/1UDGQFqvcIimwADLrlxdZzslt8QveC0ya/view?usp=sharing) with the queries.
---
I've made server changes to add database functionality.
Changes:
- .gitignore : added config.json that currently has the database config info.
- server/app.js: added …
=> Added database config + initial functional test environ.

client/src/components/messenger/ChatItem.js, client/src/components/messenger/Chats.js, client/src/components/messenger/ContactItem.js, client/src/components/messenger/Contacts.js, client/src/styles/messenger.css
Created a design for the contact and chat list items
Chat items will have the chat image along with the chat topic, the last message sent, time it was sent and a count of the unread messages.
Contact items will have the contact's image as well as their username and status (online, offline, away etc)
=> Design chat and contact items

server/config/sample_config.json
- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like
---
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration
---
I added some extra setting (dialectOptions, timezone and changed define:timestamps to true so sequelize can manage created_at and updated_at) to the server/config/sample_config.json file that I included in my config during development. Excluding them may have broken the database functionality for other users.
=> Updated sample_config.json with a few extra settings.

server/models/index.js, server/queries/create-tables.sql
- Fixed migration script by removing extra default value from boolean field
- Use path.join to make the path to the config file
=> Apply some small fixes

server/docker-compose.yml
---
This PR creates a docker compose file for the postgres container, which makes it easier to manage the variables passed to launch and start the container.
=> add docker compose file to easily edit and launch container

server/routes/contacts.js, server/routes/conversations.js, server/routes/messages.js, server/routes/participants.js, server/routes/signinOptions.js, server/routes/users.js
- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like
---
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration
---
This change updates the controller imports in the server/routes files to use the upper camel case names of the server/controllers files. Fixes Issue #33
=> Fixed controller imports in route files

.editorconfig, README.md, client/README.md, server/README.MD
The new files were previewed in VSCode after updates were made.
---
I've added more useful instructions to the main README file and created a README file for the client.
=> Updated the README files

.vscode/launch.json, server/README.MD, server/queries/create-tables.sql
- Fixed the readme
- Fixed the schema (added created_at)
- Added debug config for vs code
=> Fixed small things to make it work

package.json
I ran `npm run dev` from the root of the project and it started the server then the client and opened the client in a browser, with no error messages.
---
Added the concurrently package and a new package.json at the root of the project to start server and client with one command:
`npm run dev`
=> Added ability to start server and client with one command from project root

README.md, client/README.md, package.json, server/README.MD, server/config/sample_config.json, server/env.sample, server/seeders/20211122205724-dev_seeder.js
I cloned the repo to a new location and followed the instructions and at the end was able to sign in and view my new BFFs and our convos.
---
- Added NODE_ENV to env.sample (needed by seeder)
-  Added userInfo to sample_config dev. settings for seeder
- Added a seeder that :
- creates a user (main user) + signinoption using the info from config.json
- creates 10 other users + signinoptions
- adds the 1st 5 extra users as the main user's contacts
- adds 6 convos (1 w/ each contact and 1 w/ all together)
- adds messages to all convos
- Added scripts to:
- install all dependencies and runs docker compose 
- seed the db
- start the db docker container
- migrate and seed the db in 1 command
- start the docker container and run the app in dev. mode
- Updated …
=> testing qol improvement 🥳

server/env.sample
=> Fixed env file sample

server/config/config.js, server/env.sample, server/models/index.js, server/routes/loginStrategies/facebookStrategy.js, server/routes/loginStrategies/googleStrategy.js
I started the app locally, logged in and navigated around. The login and database access were successful.
---
- Removed the facebook and google callback vars from the env file
- Now setting these values dynamically in server/config/config.js file
- in development the values are auto set to "http://localhost:5000/<callback-path>"
- else they're set to "<process.env.HOME_URL>/<callback-path>"
- Using these dynamic values in the loginStrategies
closes #67
=> Callback config fix

client/src/components/login/Login.js, server/bin/www, server/routes/loginAuth.js
- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like
---
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration
---
- Only Google's social login is required for the application to work. Twitter and Facebook are now optional.
- The front end UI has been updated to only display the configured social logins.
#68
=> relaxed login requirements

server/config/config.js, server/models/index.js
I deleted my existing db, then followed the README.md file to setup and seed a new one. It created my account, my friends, convos, etc. I was able to log in, view my contact list, convo list, messages and send new messages.
---
I made the config file export the DB config by default so it wouldn't have to be accessed via `require(path.join(__dirname, "..", "config", "config.js")).db` in the models/index.js file and the .sequelizerc file wouldn't cause an error when starting from scratch.
=> Fix db config for fresh databases

client/src/components/messenger/Contacts.js, client/src/components/messenger/Conversations.js, client/src/components/messenger/Messenger.js, client/src/components/messenger/SearchBox.js, client/src/components/messenger/hooks/SearchContext.js
=> feat:🔍implement search for contacts and chats

client/package.json, client/src/components/messenger/Chat.js, client/src/components/messenger/Messenger.js, client/src/components/messenger/Navbar.js, client/src/components/messenger/Sidebar.js, client/src/styles/chat.css
---
This PR adds an emoji picker to allow the user to add emojis to the their messages. The picker can be accessed by clicking the button of smiley face across from the text box.
Moved theme switcher a level up to avoid theme switching inconsistencies between the navbar and the sidebar. This was not a critical error as it would only occur if the user's screen size where to change dynamically, which is assumed to not happen.
=> feat:🤩add emoji picker for the chat😎

client/src/components/login/Login.js, client/src/components/messenger/Chat.js, client/src/components/messenger/Conversations.js, client/src/styles/chat.css, client/src/styles/login.css, client/src/styles/main_panel.css, client/src/styles/style.css
---
- remove background image from the app
- load a placeholder image for conversations
- chat icon and dialog will reflect the conversation placeholder image
closes #81
=> [Style] remove background image

client/src/components/messenger/Chat.js, client/src/components/messenger/ContactItem.js, client/src/components/messenger/Contacts.js, client/src/components/messenger/ConversationItem.js, client/src/components/messenger/Conversations.js, client/src/components/messenger/Messenger.js, client/src/components/messenger/controllers/Conversations.js, client/src/components/messenger/dialogs/AlertDialog.js, client/src/redux-store/conversationSlice.js, client/src/styles/main_panel.css, server/controllers/Conversations.js
---
- the conversation list is now sorted by most recent activity (when not being searched)
activity is defined by most recent messages or most recently created
- refactored how the alert dialog works to avoid duplicate markup code
closes #85
=> feat:📑sort convo list by recent activity

client/src/components/messenger/Contacts.js, client/src/components/messenger/Conversations.js, client/src/components/messenger/controllers/Contacts.js, client/src/components/messenger/dialogs/AddContactDialog.js, client/src/components/messenger/dialogs/AddConversationDialog.js, server/controllers/Contacts.js
---
User is now prompted to add a contact before creating a conversation if their contact list is empty.
closes #88
=> [Feature] 🧑‍💻allow user to add a contact before creating conversation
